---
# Source: prometheus/templates/kube-state-metrics-clusterrole.yaml

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: prometheus
    chart: prometheus-4.5.0
    component: "kube-state-metrics"
    heritage: Tiller
    release: RELEASE-NAME
  name: RELEASE-NAME-prometheus-kube-state-metrics
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - pods
      - services
      - resourcequotas
      - replicationcontrollers
      - limitranges
    verbs:
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - daemonsets
      - deployments
      - replicasets
    verbs:
      - list
      - watch

---
# Source: prometheus/templates/kube-state-metrics-clusterrolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: prometheus
    chart: prometheus-4.5.0
    component: "kube-state-metrics"
    heritage: Tiller
    release: RELEASE-NAME
  name: RELEASE-NAME-prometheus-kube-state-metrics
subjects:
  - kind: ServiceAccount
    name: RELEASE-NAME-prometheus-kube-state-metrics
    namespace: NAMESPACE
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: RELEASE-NAME-prometheus-kube-state-metrics

---
# Source: prometheus/templates/kube-state-metrics-deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: prometheus
    chart: prometheus-4.5.0
    component: "kube-state-metrics"
    heritage: Tiller
    release: RELEASE-NAME
  name: RELEASE-NAME-prometheus-kube-state-metrics
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
        component: "kube-state-metrics"
        release: RELEASE-NAME
    spec:
      serviceAccountName: RELEASE-NAME-prometheus-kube-state-metrics
      containers:
        - name: prometheus-kube-state-metrics
          image: "gcr.io/google_containers/kube-state-metrics:v0.4.1"
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: metrics
              containerPort: 8080
          resources:
            {}

---
# Source: prometheus/templates/kube-state-metrics-serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus
    chart: prometheus-4.5.0
    component: "kube-state-metrics"
    heritage: Tiller
    release: RELEASE-NAME
  name: RELEASE-NAME-prometheus-kube-state-metrics

---
# Source: prometheus/templates/kube-state-metrics-svc.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"

  labels:
    app: prometheus
    chart: prometheus-4.5.0
    component: "kube-state-metrics"
    heritage: Tiller
    release: RELEASE-NAME
  name: RELEASE-NAME-prometheus-kube-state-metrics
spec:
  clusterIP: None
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: prometheus
    component: "kube-state-metrics"
    release: RELEASE-NAME
  type: "ClusterIP"

